env:
  browser: true
  es6: true
settings:
  react:
    version: '16'
extends:
  - 'plugin:react/recommended'
  - 'plugin:@typescript-eslint/eslint-recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
rules:
  indent:
    - error
    - 4
  linebreak-style:
    - error
    - unix
  quotes:
    - warn
    - double
  semi:
    - error
    - never
  object-curly-spacing:
    - warn
    - never
    - "objectsInObjects": true
  object-curly-newline:
    - warn
    - "multiline": true
  lines-between-class-members:
    - warn
    - always
    - "exceptAfterSingleLine": true
  no-console:
    - error
  '@typescript-eslint/no-explicit-any':
    - error
  '@typescript-eslint/consistent-type-assertions':
    - error
    - assertionStyle: as
      objectLiteralTypeAssertions: 'never'

