name: Test
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - uses: actions/setup-node@v1.1.0
      with:
        node-version: '12.x'
    
    - run: npm install
    - run: CI=true npm test
